import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F0E6',
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  coinSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  coinIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E2B84B',
    borderWidth: 1,
    borderColor: '#C6941D',
  },
  coinBox: {
    minWidth: 70,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#FFF7E4',
    borderWidth: 1,
    borderColor: '#D9C79A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  coinText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4A3A1A',
  },
  levelSection: {
    alignItems: 'center',
  },
  levelLabel: {
    fontSize: 13,
    color: '#5A4A2A',
    marginBottom: 2,
  },
  levelNumber: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2E2412',
  },
  menuButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FFF7E4',
    borderWidth: 1,
    borderColor: '#D9C79A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuLine: {
    width: 16,
    height: 2,
    backgroundColor: '#4A3A1A',
    borderRadius: 2,
    marginVertical: 1.5,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  movesSection: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  movesLabel: {
    fontSize: 14,
    color: '#3A2D17',
    fontWeight: '500',
  },
  movesNumber: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2E2412',
  },
  deckSection: {
    alignItems: 'flex-end',
  },
  deckCard: {
    width: 58,
    height: 78,
    borderRadius: 12,
    backgroundColor: '#D9E6F2',
    borderWidth: 2,
    borderColor: '#8CA3B8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deckText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#35506B',
  },
  placeholdersRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
   // marginBottom: 22,
  },
  cardsArea: {
    flexDirection: 'row',
    justifyContent: 'space-between',
   // marginBottom: 22,
  },
  cardPileBox: {
    width: '48%',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3A2D17',
    marginBottom: 10,
  },
  hiddenPile: {
    width: '100%',
    height: 140,
    borderRadius: 16,
    backgroundColor: '#9AA6B2',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#6C7884',
  },
  hiddenText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  openPile: {
    width: '100%',
    height: 140,
    borderRadius: 16,
    backgroundColor: '#EAF4E6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#A7C39B',
  },
  openText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3E5C33',
  },
  bottomButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 'auto',
    marginBottom: 18,
  },
  actionButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#FFF7E4',
    borderWidth: 1,
    borderColor: '#D9C79A',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  actionText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3A2D17',
  },
})
